// Barrel. Everything that touches the database imports from here, never from
// schema.ts directly — schema.ts is regenerated by `@better-auth/cli generate`
// and anything added to it by hand is lost on the next run.
export * from "./schema";
export * from "./audit";
